version: '3.9'

name: 'agnos-backend'

services:
  server:
    container_name: server
    build:
      dockerfile: ./containers/server/Dockerfile
      context: .
    env_file:
      - ./environments/server/.env
      - ./environments/database/.env
    networks:
      - agnos
  database:
    container_name: database
    image: postgres:16-alpine
    env_file:
      - ./environments/database/.env
    ports:
      - 5432:5432
    networks:
      - agnos
  nginx:
    container_name: gateway
    build:
      dockerfile: ./containers/gateway/Dockerfile
      context: .
    ports:
      - 3000:3000
    networks:
      - agnos

networks:
  agnos:
    name: agnos
    external: false
